### ISSUE TITLE
Could you allow php 5.3?

### ISSUE THREAD

**Issue by eduardor2k** [ChristiaanBye/polyfill-each#1]
Hi, could you allow 5.3 versions of php to use this package?

**Comment by ChristiaanBye** [comment]
Hello! I remember there being some limitation as to why I couldn't allow 5.3, but I honestly can't remember what was getting in the way

I'll take a look soon and get back to you!

**Comment by ChristiaanBye** [comment]
Sorry that it took quite a while to get back to you @eduardor2k. I have performed quite some testing, but for the life of me cannot figure out what was holding me back when I initially wrote it. Likely it was an infrastructure limitation rather than code itself

Anyhow, I have added support for 5.3 in the latest commit. Enjoy!
